--
-- TABLE STRUCTURE FOR TABLE `ROLE`
--

CREATE TABLE `ROLE` (
  `ROLE_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` VARCHAR(40) NOT NULL,
  `ROLE_DESCRIPTION` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ROLE_ID`),
  UNIQUE KEY `ROLE_NAME` (`ROLE_NAME`)
) ENGINE=INNODB;

--
-- TABLE STRUCTURE FOR TABLE `URL_RULE`
--

CREATE TABLE IF NOT EXISTS `URL_RULE` (
  `URL_RULE_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(40) NOT NULL,
  `METHOD` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`URL_RULE_ID`)
) ENGINE=INNODB;

--
-- TABLE STRUCTURE FOR TABLE `ROLE_URL_RULE`
--

CREATE TABLE IF NOT EXISTS `ROLE_URL_RULE` (
  `ROLE_ID` BIGINT(20) NOT NULL,
  `URL_RULE_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ROLE_ID`,`URL_RULE_ID`),
  KEY `FK89656D75DAA91374` (`ROLE_ID`),
  KEY `FK89656D75440A0FBF` (`URL_RULE_ID`)
) ENGINE=INNODB;

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `USERS` (
  `USER_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(30) NOT NULL UNIQUE,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `FIRST_NAME` VARCHAR(30) NOT NULL UNIQUE,
  `LAST_NAME` VARCHAR(30) NOT NULL UNIQUE,
  `ENABLED` BIT(1) NOT NULL DEFAULT B'1',
  `ACCOUNT_NON_EXPIRED` BIT(1) NOT NULL DEFAULT B'1',
  `ACCOUNT_NON_LOCKED` BIT(1) NOT NULL DEFAULT B'1',
  `CREDENTIALS_NON_EXPIRED` BIT(1) NOT NULL DEFAULT B'1',
  `CREATION_DATE`  BIGINT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=INNODB;

--
-- Table Structure for table 'users_role'
--

CREATE TABLE IF NOT EXISTS `USERS_ROLE` (
  `USER_ID` BIGINT(20) NOT NULL,
  `ROLE_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`USER_ID`,`ROLE_ID`),
  KEY `FK_USERS_ROLE_USERS_ID` (`USER_ID`),
  KEY `FK_USERS_ROLE_ROLE_ID` (`ROLE_ID`)
) ENGINE=INNODB;

--
-- Table structure for table `product`
--

CREATE TABLE IF NOT EXISTS `PRODUCT` (
  `PRODUCT_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `PRODUCT_CODE` VARCHAR(40) NOT NULL,
   PRIMARY KEY (`PRODUCT_ID`),
   UNIQUE KEY `PRODUCT_CODE` (`PRODUCT_CODE`)
) ENGINE=INNODB;

--
-- Table structure for table 'category'
--

CREATE TABLE IF NOT EXISTS `CATEGORY` (
  `CATEGORY_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CATEGORY_NAME` VARCHAR(40) NOT NULL,
   PRIMARY KEY (`CATEGORY_ID`),
   UNIQUE KEY `CATEGORY_NAME` (`CATEGORY_NAME`)
) ENGINE=INNODB;


--
-- Table structure for table 'sub_category'
--

CREATE TABLE IF NOT EXISTS `SUB_CATEGORY` (
  `SUB_CATEGORY_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `SUB_CATEGORY_NAME` VARCHAR(40) NOT NULL,
   PRIMARY KEY (`SUB_CATEGORY_ID`),
   UNIQUE KEY `SUB_CATEGORY_NAME` (`SUB_CATEGORY_NAME`)
) ENGINE=INNODB;

--
-- Table structure for table 'product_category'
--

CREATE TABLE IF NOT EXISTS `PRODUCT_CATEGORY` (
  `PRODUCT_CATEGORY_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` BIGINT(20) NOT NULL,
  `CATEGORY_ID` BIGINT(20) NOT NULL,
  `CATEGORY_RAW_DATA` VARCHAR(40),
  `CATEGORY_TARGET_DATA` VARCHAR(40),
  `CREATED_DATE` BIGINT NULL,
  `LAST_MODIFIED_DATE` BIGINT NULL,
  PRIMARY KEY (`PRODUCT_CATEGORY_ID`,`PRODUCT_ID`,`CATEGORY_ID`),
  KEY `FK_PRODUCT_CATEGORY_PRODUCT_ID` (`PRODUCT_ID`),
  KEY `FK_PRODUCT_CATEGORY_CATEGORY_ID` (`CATEGORY_ID`)
) ENGINE=INNODB;

--
-- Table structure for table 'sub_category_raw_data'
--

CREATE TABLE IF NOT EXISTS `SUB_CATEGORY_DATA` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `PRODUCT_CATEGORY_ID` BIGINT(20) NOT NULL,
  `SUB_CATEGORY_ID` BIGINT(20) NOT NULL,
  `SUB_CATEGORY_RAW_DATA` VARCHAR(40),
  `SUB_CATEGORY_TARGET_DATA` VARCHAR(40),
  `SUB_CATEGORY_CALCULATED_DATA` VARCHAR(40),
  `CREATED_DATE`  BIGINT NULL,
  `LAST_MODIFIED_DATE` BIGINT NULL,
  PRIMARY KEY (`ID`,`PRODUCT_CATEGORY_ID`,`SUB_CATEGORY_ID`),
  KEY `FK_SCRD_PRODUCT_CATEGORY_ID` (`PRODUCT_CATEGORY_ID`),
  KEY `FK_SCRD_SUB_CATEGORY_ID` (`SUB_CATEGORY_ID`)
) ENGINE=INNODB;