ALTER TABLE PRODUCT AUTO_INCREMENT = 1;

ALTER TABLE CATEGORY AUTO_INCREMENT = 1;

ALTER TABLE PRODUCT_CATEGORY AUTO_INCREMENT = 1;

ALTER TABLE SUB_CATEGORY AUTO_INCREMENT = 1;

ALTER TABLE SUB_CATEGORY_DATA AUTO_INCREMENT = 1;